import type { ModuleDef, ModuleKey } from './types';
import * as E from './enums';

const USER_REL  = { table: 'users',    labelKey: 'full_name',  orderBy: 'full_name' } as const;
const CLIENT_REL= { table: 'clients',  labelKey: 'brand_name', orderBy: 'brand_name' } as const;
const PROJECT_REL={ table: 'projects', labelKey: 'name',       orderBy: 'name' } as const;

/* =====================================================================
   Every module is DATA. Adding a module, a field, a view mode or a
   filterable date is an edit to this file — never a new page component.
   The four view modes, the inline editors, the filter bar, the detail
   page, the export and the permission checks all read from here.
   ===================================================================== */

export const MODULES: Record<string, ModuleDef> = {
  /* ---------------------------------------------------------------- */
  clients: {
    key: 'clients', table: 'clients', label: 'Clients', singular: 'Client',
    titleField: 'brand_name',
    views: ['list', 'kanban', 'timeline'], defaultView: 'list',
    kanbanGroupBy: 'status', kanbanGroupOptions: ['status', 'health', 'priority', 'account_manager_id'],
    timeline: { start: 'contract_start_date', end: 'contract_end_date', groupBy: 'account_manager_id' },
    dateFields: [
      { key: 'renewal_date', label: 'Renewal date' },
      { key: 'contract_end_date', label: 'Contract end' },
      { key: 'contract_start_date', label: 'Contract start' },
      { key: 'onboarding_date', label: 'Onboarded' },
      { key: 'created_at', label: 'Created' },
    ],
    select: '*, account_manager:users!clients_account_manager_id_fkey(id,full_name,avatar_url)',
    defaultSort: [{ key: 'brand_name', desc: false }],
    clientScoped: false, softDelete: true,
    searchFields: ['brand_name', 'legal_name', 'client_code', 'industry', 'city'],
    fields: [
      { key: 'client_code', label: 'Code', type: 'text', editable: false, width: 90, section: 'Identity' },
      { key: 'brand_name', label: 'Brand', type: 'text', required: true, width: 180, section: 'Identity' },
      { key: 'legal_name', label: 'Legal name', type: 'text', required: true, width: 200, section: 'Identity' },
      { key: 'industry', label: 'Industry', type: 'text', width: 140, section: 'Identity' },
      { key: 'website', label: 'Website', type: 'url', inList: false, section: 'Identity' },
      { key: 'city', label: 'City', type: 'text', width: 120, section: 'Location' },
      { key: 'country', label: 'Country', type: 'text', inList: false, section: 'Location' },
      { key: 'timezone', label: 'Timezone', type: 'text', inList: false, section: 'Location',
        help: 'Every date this client sees is rendered in this zone. Changing it re-points scheduled posts.' },
      { key: 'status', label: 'Status', type: 'select', options: E.CLIENT_STATUS, required: true, width: 120, section: 'Lifecycle' },
      { key: 'health', label: 'Health', type: 'select', options: E.HEALTH, editable: false, width: 90, section: 'Lifecycle',
        help: 'Rolled up from project health. Not directly editable.' },
      { key: 'priority', label: 'Priority', type: 'select', options: E.PRIORITY, width: 100, section: 'Lifecycle' },
      { key: 'account_manager_id', label: 'Account manager', type: 'user', relation: USER_REL, width: 160,
        section: 'Ownership', permissionAction: 'assign' },
      { key: 'source', label: 'Source', type: 'text', inList: false, section: 'Lifecycle' },
      { key: 'onboarding_date', label: 'Onboarded', type: 'date', inList: false, section: 'Contract' },
      { key: 'contract_start_date', label: 'Contract start', type: 'date', width: 130, section: 'Contract' },
      { key: 'contract_end_date', label: 'Contract end', type: 'date', width: 130, section: 'Contract' },
      { key: 'renewal_date', label: 'Renewal', type: 'date', width: 120, section: 'Contract' },
      { key: 'notice_period_days', label: 'Notice period (days)', type: 'number', inList: false, section: 'Contract' },
      { key: 'service_tags', label: 'Services', type: 'tags', inList: false, section: 'Scope' },
      { key: 'notes', label: 'Notes', type: 'longtext', inList: false, section: 'Notes' },
    ],
  },

  /* ---------------------------------------------------------------- */
  leads: {
    key: 'leads', table: 'leads', label: 'Leads', singular: 'Lead',
    titleField: 'company',
    views: ['list', 'kanban', 'calendar', 'timeline'], defaultView: 'kanban',
    kanbanGroupBy: 'stage', kanbanGroupOptions: ['stage', 'priority', 'owner_id'],
    calendar: { start: 'next_action_date', allDay: true },
    timeline: { start: 'first_contacted_on', end: 'expected_start_date', groupBy: 'owner_id' },
    dateFields: [
      { key: 'next_action_date', label: 'Next action' },
      { key: 'expected_start_date', label: 'Expected start' },
      { key: 'last_activity_on', label: 'Last activity' },
      { key: 'created_at', label: 'Created' },
    ],
    select: '*, owner:users!leads_owner_id_fkey(id,full_name)',
    defaultSort: [{ key: 'next_action_date', desc: false }],
    clientScoped: false, softDelete: true,
    searchFields: ['company', 'brand_name', 'contact_name', 'contact_email'],
    fields: [
      { key: 'company', label: 'Company', type: 'text', required: true, width: 190, section: 'Company' },
      { key: 'brand_name', label: 'Brand', type: 'text', width: 140, section: 'Company' },
      { key: 'industry', label: 'Industry', type: 'text', width: 130, section: 'Company' },
      { key: 'city', label: 'City', type: 'text', inList: false, section: 'Company' },
      { key: 'website', label: 'Website', type: 'url', inList: false, section: 'Company' },
      { key: 'contact_name', label: 'Contact', type: 'text', width: 150, section: 'Contact' },
      { key: 'designation', label: 'Designation', type: 'text', inList: false, section: 'Contact' },
      { key: 'contact_email', label: 'Email', type: 'email', width: 190, section: 'Contact' },
      { key: 'contact_phone', label: 'Phone', type: 'phone', inList: false, section: 'Contact' },
      { key: 'stage', label: 'Stage', type: 'select', options: E.LEAD_STAGE, required: true, width: 130, section: 'Pipeline' },
      { key: 'priority', label: 'Priority', type: 'select', options: E.PRIORITY, width: 100, section: 'Pipeline' },
      { key: 'source', label: 'Source', type: 'text', width: 130, section: 'Pipeline' },
      { key: 'owner_id', label: 'Owner', type: 'user', relation: USER_REL, width: 150, section: 'Pipeline', permissionAction: 'assign' },
      { key: 'next_action_date', label: 'Next action', type: 'date', width: 120, section: 'Pipeline' },
      { key: 'next_action_note', label: 'Next action note', type: 'text', inList: false, section: 'Pipeline' },
      { key: 'expected_start_date', label: 'Expected start', type: 'date', width: 130, section: 'Pipeline' },
      { key: 'service_interest', label: 'Interested in', type: 'tags', inList: false, section: 'Scope' },
      { key: 'lost_reason', label: 'Lost reason', type: 'text', inList: false, section: 'Pipeline' },
      { key: 'notes', label: 'Notes', type: 'longtext', inList: false, section: 'Notes' },
    ],
  },

  /* ---------------------------------------------------------------- */
  projects: {
    key: 'projects', table: 'projects', label: 'Projects', singular: 'Project',
    titleField: 'name',
    views: ['list', 'kanban', 'timeline'], defaultView: 'list',
    kanbanGroupBy: 'status', kanbanGroupOptions: ['status', 'health', 'type', 'manager_id'],
    timeline: { start: 'start_date', end: 'end_date', groupBy: 'client_id' },
    dateFields: [
      { key: 'start_date', label: 'Start' }, { key: 'end_date', label: 'End' },
      { key: 'created_at', label: 'Created' },
    ],
    select: '*, client:clients(id,brand_name,timezone), manager:users!projects_manager_id_fkey(id,full_name)',
    defaultSort: [{ key: 'start_date', desc: true }],
    clientScoped: true, softDelete: true,
    searchFields: ['name', 'code', 'description'],
    fields: [
      { key: 'name', label: 'Project', type: 'text', required: true, width: 220, section: 'Identity' },
      { key: 'client_id', label: 'Client', type: 'client', relation: CLIENT_REL, required: true, width: 160, section: 'Identity' },
      { key: 'type', label: 'Type', type: 'select', options: E.PROJECT_TYPE, required: true, width: 110, section: 'Identity' },
      { key: 'status', label: 'Status', type: 'select', options: E.PROJECT_STATUS, required: true, width: 120, section: 'Lifecycle' },
      { key: 'health', label: 'Health', type: 'select', options: E.HEALTH, editable: false, width: 90, section: 'Lifecycle',
        help: 'Rolled up from deliverable slippage.' },
      { key: 'manager_id', label: 'Manager', type: 'user', relation: USER_REL, width: 150, section: 'Ownership', permissionAction: 'assign' },
      { key: 'start_date', label: 'Start', type: 'date', width: 120, section: 'Dates' },
      { key: 'end_date', label: 'End', type: 'date', width: 120, section: 'Dates' },
      { key: 'health_note', label: 'Health note', type: 'longtext', inList: false, section: 'Lifecycle' },
      { key: 'description', label: 'Description', type: 'longtext', inList: false, section: 'Notes' },
    ],
  },

  /* ---------------------------------------------------------------- */
  deliverables: {
    key: 'deliverables', table: 'deliverables', label: 'Deliverables', singular: 'Deliverable',
    titleField: 'title',
    views: ['list', 'kanban', 'calendar', 'timeline'], defaultView: 'list',
    kanbanGroupBy: 'status', kanbanGroupOptions: ['status', 'approval_status', 'owner_id', 'client_id', 'type'],
    calendar: { start: 'due_date', allDay: true },
    timeline: { start: 'due_date', end: 'sla_due_date', groupBy: 'client_id' },
    dateFields: [
      { key: 'due_date', label: 'Due date' }, { key: 'sla_due_date', label: 'SLA due' },
      { key: 'delivered_at', label: 'Delivered' }, { key: 'created_at', label: 'Created' },
    ],
    select: '*, client:clients(id,brand_name,timezone), project:projects(id,name), owner:users!deliverables_owner_id_fkey(id,full_name), reviewer:users!deliverables_reviewer_id_fkey(id,full_name)',
    defaultSort: [{ key: 'due_date', desc: false }],
    clientScoped: true, softDelete: true,
    searchFields: ['title', 'type', 'brief'],
    fields: [
      { key: 'title', label: 'Deliverable', type: 'text', required: true, width: 220, section: 'Identity' },
      { key: 'type', label: 'Type', type: 'text', required: true, width: 110, section: 'Identity' },
      { key: 'client_id', label: 'Client', type: 'client', relation: CLIENT_REL, width: 150,
        inheritedFrom: 'project', section: 'Identity',
        help: 'Inherited from the project. Change it on the project.' },
      { key: 'project_id', label: 'Project', type: 'relation', relation: PROJECT_REL, required: true, width: 160, section: 'Identity' },
      { key: 'qty', label: 'Qty', type: 'number', width: 70, section: 'Scope' },
      { key: 'platform', label: 'Platform', type: 'select', options: E.PLATFORM, width: 120, section: 'Scope' },
      { key: 'status', label: 'Status', type: 'select', options: E.WORK_STATUS, required: true, width: 130, section: 'Progress' },
      { key: 'approval_status', label: 'Approval', type: 'select', options: E.APPROVAL_STATE, width: 140,
        section: 'Progress', permissionAction: 'approve' },
      { key: 'priority', label: 'Priority', type: 'select', options: E.PRIORITY, width: 100, section: 'Progress' },
      { key: 'owner_id', label: 'Owner', type: 'user', relation: USER_REL, width: 150, section: 'Ownership', permissionAction: 'assign' },
      { key: 'reviewer_id', label: 'Reviewer', type: 'user', relation: USER_REL, width: 150, section: 'Ownership', permissionAction: 'assign' },
      { key: 'due_date', label: 'Due', type: 'date', width: 110, section: 'Dates' },
      { key: 'sla_due_date', label: 'SLA due', type: 'date', editable: false, width: 110, section: 'Dates',
        help: 'Derived from the client service scope SLA.' },
      { key: 'delivered_at', label: 'Delivered', type: 'datetime', editable: false, inList: false, section: 'Dates' },
      { key: 'current_version', label: 'Version', type: 'number', editable: false, width: 80, section: 'Progress' },
      { key: 'review_rounds_allowed', label: 'Rounds allowed', type: 'number', editable: false, inList: false, section: 'Scope' },
      { key: 'review_rounds_used', label: 'Rounds used', type: 'number', editable: false, inList: false, section: 'Scope' },
      { key: 'brief', label: 'Brief', type: 'longtext', inList: false, section: 'Brief' },
    ],
  },

  /* ---------------------------------------------------------------- */
  tasks: {
    key: 'tasks', table: 'tasks', label: 'Tasks', singular: 'Task',
    titleField: 'title',
    views: ['list', 'kanban', 'calendar', 'timeline'], defaultView: 'list',
    kanbanGroupBy: 'status', kanbanGroupOptions: ['status', 'assignee_id', 'client_id', 'priority', 'task_type'],
    calendar: { start: 'due_date', allDay: true },
    timeline: { start: 'start_date', end: 'due_date', groupBy: 'assignee_id' },
    dateFields: [
      { key: 'due_date', label: 'Due date' }, { key: 'start_date', label: 'Start date' },
      { key: 'completed_at', label: 'Completed' }, { key: 'created_at', label: 'Created' },
    ],
    select: '*, client:clients(id,brand_name), project:projects(id,name), deliverable:deliverables(id,title), assignee:users!tasks_assignee_id_fkey(id,full_name,avatar_url), reviewer:users!tasks_reviewer_id_fkey(id,full_name)',
    defaultSort: [{ key: 'due_date', desc: false }],
    clientScoped: true, softDelete: true,
    searchFields: ['title', 'description', 'task_type'],
    fields: [
      { key: 'title', label: 'Task', type: 'text', required: true, width: 260, section: 'Identity' },
      { key: 'task_type', label: 'Type', type: 'text', width: 110, section: 'Identity' },
      { key: 'client_id', label: 'Client', type: 'client', relation: CLIENT_REL, width: 140,
        inheritedFrom: 'deliverable', section: 'Identity',
        help: 'Inherited from the deliverable. Change it there.' },
      { key: 'deliverable_id', label: 'Deliverable', type: 'relation',
        relation: { table: 'deliverables', labelKey: 'title', orderBy: 'title' }, width: 170, section: 'Identity' },
      { key: 'assignee_id', label: 'Assignee', type: 'user', relation: USER_REL, width: 150,
        section: 'Ownership', permissionAction: 'assign',
        help: 'Assigning someone on approved leave raises a warning and suggests alternatives.' },
      { key: 'reviewer_id', label: 'Reviewer', type: 'user', relation: USER_REL, width: 150, section: 'Ownership', permissionAction: 'assign' },
      { key: 'status', label: 'Status', type: 'select', options: E.WORK_STATUS, required: true, width: 130, section: 'Progress' },
      { key: 'priority', label: 'Priority', type: 'select', options: E.PRIORITY, width: 100, section: 'Progress' },
      { key: 'is_blocked', label: 'Blocked', type: 'boolean', width: 80, section: 'Progress' },
      { key: 'block_reason', label: 'Block reason', type: 'text', inList: false, section: 'Progress',
        help: 'Required whenever the task is marked blocked.' },
      { key: 'start_date', label: 'Start', type: 'date', width: 110, section: 'Dates' },
      { key: 'due_date', label: 'Due', type: 'date', width: 110, section: 'Dates',
        help: 'Moving this cascades every dependent task by the same working-day delta.' },
      { key: 'estimated_hours', label: 'Est. hrs', type: 'number', width: 85, section: 'Workload' },
      { key: 'actual_hours', label: 'Actual hrs', type: 'number', width: 90, section: 'Workload' },
      { key: 'description', label: 'Description', type: 'longtext', inList: false, section: 'Brief' },
    ],
  },

  /* ---------------------------------------------------------------- */
  shoots: {
    key: 'shoots', table: 'shoots', label: 'Shoots', singular: 'Shoot',
    titleField: 'title',
    views: ['list', 'kanban', 'calendar', 'timeline'], defaultView: 'calendar',
    kanbanGroupBy: 'status', kanbanGroupOptions: ['status', 'type', 'client_id', 'director_id'],
    calendar: { start: 'shoot_date', allDay: false },
    timeline: { start: 'shoot_date', end: 'shoot_date', groupBy: 'director_id' },
    dateFields: [{ key: 'shoot_date', label: 'Shoot date' }, { key: 'created_at', label: 'Created' }],
    select: '*, client:clients(id,brand_name,timezone), project:projects(id,name), director:users!shoots_director_id_fkey(id,full_name), producer:users!shoots_producer_id_fkey(id,full_name)',
    defaultSort: [{ key: 'shoot_date', desc: false }],
    clientScoped: true, softDelete: true,
    searchFields: ['title', 'location_name', 'address', 'brief'],
    fields: [
      { key: 'title', label: 'Shoot', type: 'text', required: true, width: 220, section: 'Identity' },
      { key: 'client_id', label: 'Client', type: 'client', relation: CLIENT_REL, required: true, width: 150, section: 'Identity' },
      { key: 'project_id', label: 'Project', type: 'relation', relation: PROJECT_REL, inList: false, section: 'Identity' },
      { key: 'type', label: 'Type', type: 'select', options: E.SHOOT_TYPE, required: true, width: 120, section: 'Identity' },
      { key: 'status', label: 'Status', type: 'select', options: E.SHOOT_STATUS, required: true, width: 120, section: 'Schedule' },
      { key: 'shoot_date', label: 'Date', type: 'date', required: true, width: 120, section: 'Schedule',
        help: 'Changing this shifts every dependent edit, review, approval, post and equipment booking.' },
      { key: 'call_time', label: 'Call', type: 'time', width: 90, section: 'Schedule' },
      { key: 'wrap_time', label: 'Wrap', type: 'time', width: 90, section: 'Schedule' },
      { key: 'location_name', label: 'Location', type: 'text', width: 170, section: 'Location' },
      { key: 'address', label: 'Address', type: 'longtext', inList: false, section: 'Location' },
      { key: 'map_link', label: 'Map', type: 'url', inList: false, section: 'Location' },
      { key: 'director_id', label: 'Director', type: 'user', relation: USER_REL, width: 150, section: 'Crew', permissionAction: 'assign' },
      { key: 'producer_id', label: 'Producer', type: 'user', relation: USER_REL, inList: false, section: 'Crew', permissionAction: 'assign' },
      { key: 'weather_note', label: 'Weather', type: 'text', inList: false, section: 'Schedule' },
      { key: 'brief', label: 'Brief', type: 'longtext', inList: false, section: 'Brief' },
    ],
  },

  /* ---------------------------------------------------------------- */
  content_calendar: {
    key: 'content_calendar', table: 'content_calendar', label: 'Content Calendar', singular: 'Post',
    titleField: 'title',
    views: ['calendar', 'list', 'kanban', 'timeline'], defaultView: 'calendar',
    kanbanGroupBy: 'status', kanbanGroupOptions: ['status', 'approval_status', 'platform', 'content_type', 'client_id'],
    calendar: { start: 'post_at_utc', allDay: false },
    timeline: { start: 'post_date', end: 'post_date', groupBy: 'client_id' },
    dateFields: [{ key: 'post_date', label: 'Post date' }, { key: 'posted_at', label: 'Posted at' }, { key: 'created_at', label: 'Created' }],
    select: '*, client:clients(id,brand_name,timezone), owner:users!content_calendar_owner_id_fkey(id,full_name), reviewer:users!content_calendar_reviewer_id_fkey(id,full_name)',
    defaultSort: [{ key: 'post_date', desc: false }],
    clientScoped: true, softDelete: true,
    searchFields: ['title', 'hook', 'caption'],
    fields: [
      { key: 'title', label: 'Post', type: 'text', width: 200, section: 'Identity' },
      { key: 'client_id', label: 'Client', type: 'client', relation: CLIENT_REL, required: true, width: 140, section: 'Identity' },
      { key: 'platform', label: 'Platform', type: 'select', options: E.PLATFORM, required: true, width: 120, section: 'Identity' },
      { key: 'content_type', label: 'Format', type: 'select', options: E.CONTENT_TYPE, required: true, width: 110, section: 'Identity' },
      { key: 'post_date', label: 'Post date', type: 'date', required: true, width: 120, section: 'Schedule' },
      { key: 'post_time', label: 'Time', type: 'time', width: 90, section: 'Schedule' },
      { key: 'post_at_utc', label: 'Goes live (UTC)', type: 'datetime', editable: false, inList: false, section: 'Schedule',
        help: 'Derived from the post date/time in the client timezone. Filters compare this.' },
      { key: 'status', label: 'Status', type: 'select', options: E.WORK_STATUS, width: 130, section: 'Progress' },
      { key: 'approval_status', label: 'Approval', type: 'select', options: E.APPROVAL_STATE, width: 140,
        section: 'Progress', permissionAction: 'approve' },
      { key: 'owner_id', label: 'Owner', type: 'user', relation: USER_REL, width: 140, section: 'Ownership', permissionAction: 'assign' },
      { key: 'reviewer_id', label: 'Reviewer', type: 'user', relation: USER_REL, inList: false, section: 'Ownership', permissionAction: 'assign' },
      { key: 'hook', label: 'Hook', type: 'longtext', inList: false, section: 'Copy' },
      { key: 'caption', label: 'Caption', type: 'longtext', inList: false, section: 'Copy' },
      { key: 'hashtags', label: 'Hashtags', type: 'tags', inList: false, section: 'Copy' },
      { key: 'cta', label: 'CTA', type: 'text', inList: false, section: 'Copy' },
      { key: 'published_url', label: 'Published URL', type: 'url', inList: false, section: 'Result' },
      { key: 'posted_at', label: 'Posted at', type: 'datetime', inList: false, section: 'Result' },
    ],
  },

  /* ---------------------------------------------------------------- */
  campaigns: {
    key: 'campaigns', table: 'campaigns', label: 'Campaigns', singular: 'Campaign',
    titleField: 'name',
    views: ['list', 'kanban', 'timeline', 'calendar'], defaultView: 'timeline',
    kanbanGroupBy: 'status', kanbanGroupOptions: ['status', 'platform', 'objective', 'client_id'],
    timeline: { start: 'start_date', end: 'end_date', groupBy: 'client_id' },
    calendar: { start: 'start_date', allDay: true },
    dateFields: [{ key: 'start_date', label: 'Start' }, { key: 'end_date', label: 'End' }, { key: 'created_at', label: 'Created' }],
    select: '*, client:clients(id,brand_name), owner:users!campaigns_owner_id_fkey(id,full_name)',
    defaultSort: [{ key: 'start_date', desc: true }],
    clientScoped: true, softDelete: true,
    searchFields: ['name', 'notes'],
    fields: [
      { key: 'name', label: 'Campaign', type: 'text', required: true, width: 220, section: 'Identity' },
      { key: 'client_id', label: 'Client', type: 'client', relation: CLIENT_REL, required: true, width: 150, section: 'Identity' },
      { key: 'platform', label: 'Platform', type: 'select', options: E.PLATFORM, required: true, width: 120, section: 'Identity' },
      { key: 'objective', label: 'Objective', type: 'select', options: E.CAMPAIGN_OBJECTIVE, required: true, width: 130, section: 'Identity' },
      { key: 'status', label: 'Status', type: 'select', options: E.WORK_STATUS, width: 130, section: 'Progress' },
      { key: 'owner_id', label: 'Owner', type: 'user', relation: USER_REL, width: 150, section: 'Ownership', permissionAction: 'assign' },
      { key: 'start_date', label: 'Start', type: 'date', required: true, width: 120, section: 'Dates' },
      { key: 'end_date', label: 'End', type: 'date', width: 120, section: 'Dates' },
      { key: 'notes', label: 'Notes', type: 'longtext', inList: false, section: 'Notes' },
    ],
  },

  /* ---------------------------------------------------------------- */
  approvals: {
    key: 'approvals', table: 'approvals', label: 'Approvals', singular: 'Approval',
    titleField: 'entity_type',
    views: ['list', 'kanban', 'calendar'], defaultView: 'list',
    kanbanGroupBy: 'status', kanbanGroupOptions: ['status', 'level', 'approver_id', 'client_id'],
    calendar: { start: 'due_at', allDay: false },
    dateFields: [{ key: 'due_at', label: 'Due' }, { key: 'requested_at', label: 'Requested' }, { key: 'decided_at', label: 'Decided' }],
    select: '*, client:clients(id,brand_name), approver:users!approvals_approver_id_fkey(id,full_name), requester:users!approvals_requested_by_fkey(id,full_name)',
    defaultSort: [{ key: 'due_at', desc: false }],
    clientScoped: true, softDelete: true,
    searchFields: ['feedback'],
    fields: [
      { key: 'entity_type', label: 'On', type: 'text', editable: false, width: 130, section: 'Subject' },
      { key: 'client_id', label: 'Client', type: 'client', relation: CLIENT_REL, editable: false, width: 150, section: 'Subject' },
      { key: 'level', label: 'Stage', type: 'select', options: E.APPROVAL_LEVEL, editable: false, width: 110, section: 'Subject' },
      { key: 'round_no', label: 'Round', type: 'number', editable: false, width: 70, section: 'Subject' },
      { key: 'status', label: 'Decision', type: 'select', options: E.APPROVAL_STATE, width: 150,
        section: 'Decision', permissionAction: 'approve',
        help: 'Approving is a separate permission from editing.' },
      { key: 'approver_id', label: 'Approver', type: 'user', relation: USER_REL, width: 150, section: 'Decision', permissionAction: 'assign' },
      { key: 'requested_at', label: 'Requested', type: 'datetime', editable: false, width: 150, section: 'Timing' },
      { key: 'due_at', label: 'Due', type: 'datetime', width: 150, section: 'Timing' },
      { key: 'decided_at', label: 'Decided', type: 'datetime', editable: false, inList: false, section: 'Timing' },
      { key: 'feedback', label: 'Feedback', type: 'longtext', inList: false, section: 'Decision',
        help: 'Immutable once posted — an edit is recorded as a visible revision.' },
    ],
  },

  /* ---------------------------------------------------------------- */
  meetings: {
    key: 'meetings', table: 'meetings', label: 'Meetings', singular: 'Meeting',
    titleField: 'title',
    views: ['calendar', 'list', 'kanban', 'timeline'], defaultView: 'calendar',
    kanbanGroupBy: 'type', kanbanGroupOptions: ['type', 'status', 'client_id', 'organiser_id'],
    calendar: { start: 'starts_at', allDay: false },
    timeline: { start: 'starts_at', end: 'starts_at', groupBy: 'organiser_id' },
    dateFields: [{ key: 'starts_at', label: 'Starts at' }, { key: 'created_at', label: 'Created' }],
    select: '*, client:clients(id,brand_name), organiser:users!meetings_organiser_id_fkey(id,full_name)',
    defaultSort: [{ key: 'starts_at', desc: true }],
    clientScoped: true, softDelete: true,
    searchFields: ['title', 'agenda', 'minutes'],
    fields: [
      { key: 'title', label: 'Meeting', type: 'text', required: true, width: 230, section: 'Identity' },
      { key: 'client_id', label: 'Client', type: 'client', relation: CLIENT_REL, width: 150, section: 'Identity' },
      { key: 'type', label: 'Type', type: 'select', options: E.MEETING_TYPE, required: true, width: 120, section: 'Identity' },
      { key: 'starts_at', label: 'Starts', type: 'datetime', required: true, width: 165, section: 'Schedule' },
      { key: 'duration_mins', label: 'Mins', type: 'number', width: 80, section: 'Schedule' },
      { key: 'status', label: 'Status', type: 'select', options: ['Scheduled','Held','Cancelled','No Show'], width: 120, section: 'Schedule' },
      { key: 'organiser_id', label: 'Organiser', type: 'user', relation: USER_REL, width: 150, section: 'Ownership', permissionAction: 'assign' },
      { key: 'meeting_link', label: 'Link', type: 'url', inList: false, section: 'Schedule' },
      { key: 'location', label: 'Location', type: 'text', inList: false, section: 'Schedule' },
      { key: 'agenda', label: 'Agenda', type: 'longtext', inList: false, section: 'Notes' },
      { key: 'minutes', label: 'Minutes', type: 'longtext', inList: false, section: 'Notes',
        help: 'Saving minutes converts every action item into an assigned, dated task.' },
    ],
  },

  /* ---------------------------------------------------------------- */
  assets: {
    key: 'assets', table: 'assets', label: 'Assets', singular: 'Asset',
    titleField: 'name',
    views: ['list', 'kanban'], defaultView: 'list',
    kanbanGroupBy: 'type', kanbanGroupOptions: ['type', 'client_id'],
    dateFields: [{ key: 'uploaded_at', label: 'Uploaded' }, { key: 'created_at', label: 'Created' }],
    select: '*, client:clients(id,brand_name), uploader:users!assets_uploaded_by_fkey(id,full_name)',
    defaultSort: [{ key: 'uploaded_at', desc: true }],
    clientScoped: true, softDelete: true,
    searchFields: ['name'],
    fields: [
      { key: 'name', label: 'Asset', type: 'text', required: true, width: 240, section: 'Identity' },
      { key: 'client_id', label: 'Client', type: 'client', relation: CLIENT_REL, required: true, width: 150, section: 'Identity' },
      { key: 'type', label: 'Type', type: 'select', options: E.ASSET_TYPE, required: true, width: 130, section: 'Identity' },
      { key: 'file_url', label: 'File', type: 'url', width: 200, section: 'Location',
        help: 'Replacing this creates a new version — nothing is ever overwritten.' },
      { key: 'external_link', label: 'External link', type: 'url', inList: false, section: 'Location' },
      { key: 'current_version_no', label: 'Version', type: 'number', editable: false, width: 80, section: 'Versioning' },
      { key: 'is_client_visible', label: 'Client visible', type: 'boolean', width: 110, section: 'Sharing' },
      { key: 'uploaded_at', label: 'Uploaded', type: 'datetime', editable: false, width: 150, section: 'Versioning' },
    ],
  },

  /* ---------------------------------------------------------------- */
  equipment: {
    key: 'equipment', table: 'equipment', label: 'Equipment', singular: 'Item',
    titleField: 'item_name',
    views: ['list', 'kanban', 'timeline'], defaultView: 'list',
    kanbanGroupBy: 'category', kanbanGroupOptions: ['category', 'condition'],
    timeline: { start: 'created_at', end: 'created_at', groupBy: 'category' },
    dateFields: [{ key: 'created_at', label: 'Added' }],
    select: '*, custodian:users!equipment_custodian_id_fkey(id,full_name)',
    defaultSort: [{ key: 'item_name', desc: false }],
    clientScoped: false, softDelete: true,
    searchFields: ['item_name', 'asset_tag', 'serial_number', 'category'],
    fields: [
      { key: 'item_name', label: 'Item', type: 'text', required: true, width: 220, section: 'Identity' },
      { key: 'category', label: 'Category', type: 'text', width: 130, section: 'Identity' },
      { key: 'asset_tag', label: 'Asset tag', type: 'text', width: 110, section: 'Identity' },
      { key: 'serial_number', label: 'Serial', type: 'text', inList: false, section: 'Identity' },
      { key: 'condition', label: 'Condition', type: 'text', width: 110, section: 'Status' },
      { key: 'owned', label: 'Owned', type: 'boolean', width: 80, section: 'Status',
        help: 'Ownership is a status flag. This system holds no purchase or rental figures.' },
      { key: 'is_active', label: 'Active', type: 'boolean', width: 80, section: 'Status' },
      { key: 'custodian_id', label: 'Custodian', type: 'user', relation: USER_REL, width: 150, section: 'Ownership', permissionAction: 'assign' },
      { key: 'notes', label: 'Notes', type: 'longtext', inList: false, section: 'Notes' },
    ],
  },

  /* ---------------------------------------------------------------- */
  people: {
    key: 'people', table: 'users', label: 'People', singular: 'Person',
    titleField: 'full_name',
    views: ['list', 'kanban'], defaultView: 'list',
    kanbanGroupBy: 'status', kanbanGroupOptions: ['status', 'department_id', 'employment_type'],
    dateFields: [{ key: 'joined_on', label: 'Joined' }, { key: 'created_at', label: 'Created' }],
    select: '*, role:roles(id,name,level), department:departments(id,name), manager:users!users_manager_id_fkey(id,full_name)',
    defaultSort: [{ key: 'full_name', desc: false }],
    clientScoped: false, softDelete: true,
    searchFields: ['full_name', 'email', 'phone'],
    fields: [
      { key: 'full_name', label: 'Name', type: 'text', required: true, width: 190, section: 'Identity' },
      { key: 'email', label: 'Email', type: 'email', required: true, width: 210, section: 'Identity' },
      { key: 'phone', label: 'Phone', type: 'phone', inList: false, section: 'Identity' },
      { key: 'role_id', label: 'Role', type: 'relation',
        relation: { table: 'roles', labelKey: 'name', orderBy: 'sort_order' }, required: true, width: 160, section: 'Org' },
      { key: 'department_id', label: 'Department', type: 'relation',
        relation: { table: 'departments', labelKey: 'name', orderBy: 'sort_order' }, width: 150, section: 'Org' },
      { key: 'manager_id', label: 'Reports to', type: 'user', relation: USER_REL, width: 160, section: 'Org',
        help: 'A change that would create a reporting cycle is rejected by the database.' },
      { key: 'employment_type', label: 'Employment', type: 'select', options: E.EMPLOYMENT_TYPE, width: 120, section: 'Org' },
      { key: 'status', label: 'Status', type: 'select', options: E.USER_STATUS, width: 110, section: 'Org' },
      { key: 'timezone', label: 'Timezone', type: 'text', inList: false, section: 'Working' },
      { key: 'weekly_capacity_hours', label: 'Capacity (hrs/wk)', type: 'number', width: 130, section: 'Working',
        help: 'Workload planning only. This system records no compensation of any kind.' },
      { key: 'skills', label: 'Skills', type: 'tags', inList: false, section: 'Working' },
      { key: 'joined_on', label: 'Joined', type: 'date', width: 110, section: 'Org' },
    ],
  },

  /* ---------------------------------------------------------------- */
  leaves: {
    key: 'leaves', table: 'leave_requests', label: 'Leave', singular: 'Leave request',
    titleField: 'type',
    views: ['list', 'calendar', 'kanban', 'timeline'], defaultView: 'calendar',
    kanbanGroupBy: 'status', kanbanGroupOptions: ['status', 'type', 'user_id'],
    calendar: { start: 'from_date', end: 'to_date', allDay: true },
    timeline: { start: 'from_date', end: 'to_date', groupBy: 'user_id' },
    dateFields: [{ key: 'from_date', label: 'From' }, { key: 'to_date', label: 'To' }, { key: 'created_at', label: 'Requested' }],
    select: '*, person:users!leave_requests_user_id_fkey(id,full_name), approver:users!leave_requests_approver_id_fkey(id,full_name)',
    defaultSort: [{ key: 'from_date', desc: true }],
    clientScoped: false, softDelete: true,
    searchFields: ['reason'],
    fields: [
      { key: 'user_id', label: 'Person', type: 'user', relation: USER_REL, required: true, width: 170, section: 'Request' },
      { key: 'type', label: 'Type', type: 'select', options: E.LEAVE_TYPE, required: true, width: 110, section: 'Request' },
      { key: 'from_date', label: 'From', type: 'date', required: true, width: 115, section: 'Dates' },
      { key: 'to_date', label: 'To', type: 'date', required: true, width: 115, section: 'Dates' },
      { key: 'is_half_day', label: 'Half day', type: 'boolean', width: 90, section: 'Dates' },
      { key: 'status', label: 'Status', type: 'select', options: E.LEAVE_STATUS, width: 120,
        section: 'Decision', permissionAction: 'approve' },
      { key: 'approver_id', label: 'Approver', type: 'user', relation: USER_REL, width: 150, section: 'Decision' },
      { key: 'reason', label: 'Reason', type: 'longtext', inList: false, section: 'Request' },
      { key: 'decision_note', label: 'Decision note', type: 'longtext', inList: false, section: 'Decision' },
    ],
  },

  /* ---------------------------------------------------------------- */
  reports: {
    key: 'reports', table: 'client_reports', label: 'Reports', singular: 'Report',
    titleField: 'title',
    views: ['list', 'kanban', 'calendar', 'timeline'], defaultView: 'list',
    kanbanGroupBy: 'status', kanbanGroupOptions: ['status', 'approval_status', 'client_id'],
    calendar: { start: 'report_date', allDay: true },
    timeline: { start: 'period_start', end: 'period_end', groupBy: 'client_id' },
    dateFields: [
      { key: 'report_date', label: 'Report date' }, { key: 'period_start', label: 'Period start' },
      { key: 'period_end', label: 'Period end' }, { key: 'shared_at', label: 'Shared' },
    ],
    select: '*, client:clients(id,brand_name), owner:users!client_reports_owner_id_fkey(id,full_name)',
    defaultSort: [{ key: 'report_date', desc: true }],
    clientScoped: true, softDelete: true,
    searchFields: ['title', 'summary'],
    fields: [
      { key: 'title', label: 'Report', type: 'text', required: true, width: 230, section: 'Identity' },
      { key: 'client_id', label: 'Client', type: 'client', relation: CLIENT_REL, required: true, width: 150, section: 'Identity' },
      { key: 'period_start', label: 'Period start', type: 'date', required: true, width: 125, section: 'Period' },
      { key: 'period_end', label: 'Period end', type: 'date', required: true, width: 125, section: 'Period' },
      { key: 'report_date', label: 'Report date', type: 'date', width: 125, section: 'Period' },
      { key: 'status', label: 'Status', type: 'select', options: E.WORK_STATUS, width: 130, section: 'Progress' },
      { key: 'approval_status', label: 'Approval', type: 'select', options: E.APPROVAL_STATE, width: 140,
        section: 'Progress', permissionAction: 'approve' },
      { key: 'owner_id', label: 'Owner', type: 'user', relation: USER_REL, width: 150, section: 'Ownership', permissionAction: 'assign' },
      { key: 'link', label: 'Link', type: 'url', inList: false, section: 'Artefact' },
      { key: 'shared_at', label: 'Shared at', type: 'datetime', inList: false, section: 'Artefact',
        help: 'A report reaches the client portal only once approved AND shared.' },
      { key: 'summary', label: 'Summary', type: 'longtext', inList: false, section: 'Artefact' },
    ],
  },
};

export const MODULE_ORDER: ModuleKey[] = [
  'clients', 'leads', 'projects', 'deliverables', 'tasks', 'shoots',
  'content_calendar', 'campaigns', 'approvals', 'meetings', 'assets',
  'equipment', 'people', 'leaves', 'reports',
];

export function getModule(key: string): ModuleDef | undefined {
  return MODULES[key];
}
